package guessthenumbers.spring;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/start") // This means URL's start with /demo (after Application path)
public class MainController {


    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GameRepository gamerepo;

    @RequestMapping(path="/login") // Map ONLY GET Requests
    public @ResponseBody String loginUser (@RequestParam String name
            ,@RequestParam String password) {
        Games g = new Games();
        g.setPlayer(name);
        g.setPass(password);
        g.setGuesses(0);
        gamerepo.save(g);
        System.out.println(g.toString());
        return g.toString();
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Games> getAllUsers() {
        // This returns a JSON or XML with the users
        return gamerepo.findAll();
    }
}
